Add missing entry for new redelivery api
octokit/auth-app.js pull request #285
Opened 2021-05-08 06:05 UTC by kammerjaeger

Hi,

I'm trying to use the new event redelivery api, see: https://gist.github.com/bswinnerton/9ae3b432a8d649fe4890015bd0a86658
The request are not working for me because it seams to want to use the installation token when I use the endpoint:
app/hook/deliveries?status=failure

I tried it from a probot app with:
```
const octokit = await app.auth();
const result2 = await octokit.request("GET /app/hook/deliveries", { status: "failure", mediaType: { previews: [mediaPreview] } });
```

I'm not sure about the other apis, if they need an installation token or an app bearer.
What do you think?

2021-05-12 14:17 UTC, kammerjaeger commented
I agree, your last proposal sounds to me to be the best solution. I tried to somehow add the route without this PR (because of the beta) but could not find any way to do it.
Also the error message that a installation token is needed should maybe then have a line to say that: if it is new api and needs the app auth add it that way.

2021-06-20 05:05 UTC, Hbutlercapone approved these changes

2021-06-27 20:24 UTC, gr2m requested changes

2021-06-27 20:24 UTC, gr2m commented on src/requires-app-auth.ts
> +  "/app/hook/deliveries",
I decided it's not work adding all the extra logic just set JWT auth on custom paths. We might need it in future, but it's too much work and to low of a priority to work on it right now. Let's just add these paths and be done with it 😆 

Can you add the other two paths please?

```suggestion
  "/app/hook/deliveries",
  "/app/hook/deliveries/{delivery_id}",
  "/app/hook/deliveries/{delivery_id}/attempts",
```

2021-06-28 13:25 UTC, kammerjaeger commented
Thanks for the other two paths. I totally did not realize that was also needed.

2021-06-28 17:13 UTC, gr2m approved these changes

2021-06-28 20:26 UTC, merged